### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by datnguyenzzz** [datnguyenzzz/AWSCronJobScheduler#3]
Consist of 2 main component

### Scheduler

**Understand job definition from ENV variables**

- Reader which read from ENV and convert to a **CronJob** object

**Implementation of Quartz (library for scheduling)**

- Scheduler
- Job
- Trigger
- Listener
- Concurrency

### AWS SDK

**Comment by datnguyenzzz** [comment]
- [x] Need _**CronJobConfiguration**_ Component, where load ENV properties

Must be provided env:

- CRON_JOB_PROVIDER: local/s3
- CRON_JOB_LOCATION: yaml file define the cron job trigger and job's content
- HEALTH_CHECK_TIME_WINDOW
- CONSECUTIVE_ERROR_POSTPONE_THRESHOLD: const - postpone job if consecutive error exceed threhold
- PERCENTAGE_ERROR_POSTPONE_THRESHOLD: const  - postpone job if percentage's error exceed threhold
- AWS_REGION
- AWS_ACCESS_KEY
- AWS_SECRET_KEY
- AWS_CREDENTIALS_TARGET: file, in which provide aws credentials

**Comment by datnguyenzzz** [comment]
CronJob file format:

```
jobList:
  - name: "Upload to SQS #1"
    cronTrigger: "0 0 0 1 2 2/3"
    usedService: "SQS"
    messages:
      - key: "key-1"
        value: "value-1"
      - key: "key-2"
        value: "value-2"

  - name: "Upload to SQS #2"
    usedService: "SQS"
    afterJobDone: "Upload to SQS #1"
    lambdaActionFile: "abc/def/xyz.java"
  
  - name: "Upload to SQS #3"
    cronTrigger: "0 12 2 1 2/3 * *"
    usedService: "SQS"
    lambdaActionFile: "xyz/ghi/dfc.java"
```
